# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='capacity',
            field=models.FloatField(default=-100.0),
        ),
        migrations.AddField(
            model_name='content',
            name='humidity',
            field=models.FloatField(default=-100.0),
        ),
        migrations.AddField(
            model_name='content',
            name='temperature',
            field=models.FloatField(default=-100.0),
        ),
        migrations.AddField(
            model_name='content',
            name='timestamp',
            field=models.FloatField(default=-100.0),
        ),
    ]
